site_name: Scale Documentation
site_url: "https://aje.github.io/scale-docs"
nav:
  - Home: index.md
  - System Status: status.md
  - Basic Configuration: basic-config.md
  - Calibration: calibration.md
  - Advanced Settings: adv-settings.md
  - Communication Settings: communication-settings.md
copyright: Copyright &copy; 2025 by Behrouz Erfanian
theme:
  name: material
  language: en
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.path
    - search.highlight
    - navigation.footer
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search

extra:
  alternate:
    - name: English
      link: /scale-docs/
      lang: en
    - name: 中文
      link: /scale-docs/zh/
      lang: zh
